version: '3'

services:
  db:
    image: 'postgres:12.9-alpine'
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - 'postgres:/var/lib/postgresql/data'
  redis:
    image: 'redis:5-alpine'
    volumes:
      - 'redis:/data'
    container_name: rediscontainer

  sidekiq:
    depends_on:
      - 'db'
      - 'redis'
    build: .
    command: bundle exec sidekiq
    volumes:
      - '.:/clinical'

  web:
    depends_on:
      - 'db'
      - 'redis'
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0' -e development"
    ports:
      - '3000:3000'
    volumes:
      - '.:/clinical'

volumes:
  redis:
  postgres:
